# Generated by Django 4.2.21 on 2026-03-15 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias_semana', models.JSONField(default=list, help_text='Lista de dias (MON..SUN). Todos los dias seleccionados comparten hora_inicio y hora_fin.')),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='users.doctor', verbose_name='Medico')),
            ],
            options={
                'verbose_name': 'Horario',
                'verbose_name_plural': 'Horarios',
            },
        ),
        migrations.CreateModel(
            name='CitaMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cita', models.DateField()),
                ('hora_cita', models.TimeField()),
                ('motivo_cita', models.TextField()),
                ('tratamiento', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('ATENDIDA', 'Atendida'), ('CANCELADA_PACIENTE', 'Cancelada por el paciente'), ('CANCELADA_MEDICO', 'Cancelada por el medico')], default='ACTIVA', max_length=25)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='users.doctor', verbose_name='Medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='users.patient', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Cita medica',
                'verbose_name_plural': 'Citas medicas',
                'ordering': ['fecha_cita', 'hora_cita'],
            },
        ),
        migrations.AddConstraint(
            model_name='horario',
            constraint=models.CheckConstraint(check=models.Q(('hora_inicio__lt', models.F('hora_fin'))), name='chk_horario_inicio_menor_fin'),
        ),
        migrations.AddIndex(
            model_name='citamedica',
            index=models.Index(fields=['medico', 'fecha_cita', 'hora_cita'], name='idx_cita_medico_fecha_hora'),
        ),
        migrations.AddIndex(
            model_name='citamedica',
            index=models.Index(fields=['paciente', 'fecha_cita', 'hora_cita'], name='idx_cita_pac_fecha_hora'),
        ),
        migrations.AddConstraint(
            model_name='citamedica',
            constraint=models.UniqueConstraint(fields=('paciente', 'fecha_cita', 'hora_cita'), name='uq_cita_paciente_fecha_hora'),
        ),
        migrations.AddConstraint(
            model_name='citamedica',
            constraint=models.UniqueConstraint(fields=('medico', 'fecha_cita', 'hora_cita'), name='uq_cita_medico_fecha_hora'),
        ),
    ]
